#!/usr/bin/env node
'use strict';
const fs=require('fs');const path=require('path');
const ROOT=path.resolve(__dirname,'..');const DATA=path.join(ROOT,'data');const REPORTS=path.join(ROOT,'reports');
const readJson=n=>JSON.parse(fs.readFileSync(path.join(DATA,n),'utf8'));
const readOptional=n=>{try{return readJson(n);}catch{return {snapshots:{}};}};
const esc=v=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
const faNumber=v=>Number(v).toLocaleString('en-US');
const movement=v=>v==null||v===0?'-':v>0?`↑ ${v}`:`↓ ${Math.abs(v)}`;
const signed=v=>v==null?'—':v===0?'0':v>0?`+${faNumber(v)}`:`-${faNumber(Math.abs(v))}`;
const weapon=(level,delta)=>delta==null||delta===0?faNumber(level):`${faNumber(level)} (${signed(delta)})`;
const reportId=s=>s.source_report?path.basename(s.source_report,'.html'):`${s.captured_at_utc.slice(0,10)}-${s.time_iran.replace(':','')}`;
const snapshotsFile=readJson('snapshots.json');const historyFile=readJson('player-observations-history.json');const historyS05=readOptional('player-observations-history-s05.json');const currentFile=readJson('player-observations.json');const playersFile=readJson('players.json');const indexFile=readJson('index.json');
const snapshotId=process.argv[2]||snapshotsFile.current_snapshot_id;const target=(snapshotsFile.snapshots||[]).find(s=>s.snapshot_id===snapshotId);if(!target)throw new Error(`Unknown snapshot_id: ${snapshotId}`);
const ordered=[...snapshotsFile.snapshots].sort((a,b)=>a.captured_at_utc.localeCompare(b.captured_at_utc));const index=ordered.findIndex(s=>s.snapshot_id===snapshotId);const previous=index>0?ordered[index-1]:null;const next=index<ordered.length-1?ordered[index+1]:null;
const sourceSets=[historyFile,historyS05,currentFile];const getSnapshotRows=sid=>{for(const source of sourceSets){const rows=source.snapshots?.[sid];if(Array.isArray(rows))return rows;}return null;};
const rows=getSnapshotRows(snapshotId);if(!Array.isArray(rows))throw new Error(`Missing normalized rows for ${snapshotId}`);if(rows.length!==target.members)throw new Error(`${snapshotId}: rows ${rows.length} != members ${target.members}`);
const registry=new Map((playersFile.players||[]).map(p=>[p.player_id,p]));const previousRows=previous?getSnapshotRows(previous.snapshot_id)||[]:[];const previousIds=new Set(previousRows.map(r=>r.player_id));const currentIds=new Set(rows.map(r=>r.player_id));const added=[...currentIds].filter(id=>!previousIds.has(id));const removed=[...previousIds].filter(id=>!currentIds.has(id));const retained=rows.filter(r=>previousIds.has(r.player_id)).length;const totalClanMedals=rows.reduce((s,r)=>s+r.clan_medals,0);
const topKills=[...rows].filter(r=>Number.isInteger(r.kills_delta)).sort((a,b)=>b.kills_delta-a.kills_delta).slice(0,5);const topLeague=[...rows].filter(r=>Number.isInteger(r.league_medals_delta)).sort((a,b)=>b.league_medals_delta-a.league_medals_delta).slice(0,5);const getName=r=>registry.get(r.player_id)?.display_name||r.display_name||r.player_id;const getRole=r=>registry.get(r.player_id)?.role||r.role||'Member';const sourcePath=target.source_report||`/clan-leaderboard/reports/${reportId(target)}.html`;const reportsById=new Map((indexFile.reports||[]).map(r=>[r.id,r.page]));
let rowsHtml='';for(const row of [...rows].sort((a,b)=>a.rank-b.rank)){const label=row.rank_movement==null?String(row.rank):`${row.rank} (${movement(row.rank_movement)})`;const medals=row.honor_medals||{gold:0,silver:0,bronze:0};const upgrades=row.weapons?.upgrade_deltas||{};const weaponText=`${weapon(row.weapons?.['25mm']??0,upgrades['25mm'])} / ${weapon(row.weapons?.hydra??0,upgrades.hydra)} / ${weapon(row.weapons?.hellfire??0,upgrades.hellfire)}`;rowsHtml+=`<tr><td>${esc(label)}</td><td>${esc(getName(row))}</td><td>${esc(getRole(row))}</td><td>${faNumber(row.stage)}</td><td>${faNumber(row.league_medals)}</td><td>${signed(row.league_medals_delta)}</td><td>${faNumber(row.clan_medals)}</td><td>${medals.gold} / ${medals.silver} / ${medals.bronze}</td><td>${faNumber(row.total_kills)}</td><td>${signed(row.kills_delta)}</td><td>${weaponText}</td><td>${esc(row.last_online_display)}</td></tr>`;}
const prevPage=previous?reportsById.get(reportId(previous))||`../reports/${reportId(previous)}.html`:null;const nextPage=next?reportsById.get(reportId(next))||`../reports/${reportId(next)}.html`:null;const nav=`<nav class="report-nav" aria-label="گزارش‌های کلن"><a href="../archive.html">آرشیو</a>${prevPage?`<a href="${prevPage}">قبلی</a>`:'<span class="muted">قبلی</span>'}${nextPage?`<a href="${nextPage}">بعدی</a>`:'<span class="muted">بعدی</span>'}</nav>`;
const report=`<!doctype html><html lang="fa" dir="rtl" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>PERSIA · Clan Leaderboard · ${esc(target.date_persian)} · ${esc(target.time_iran)}</title><link rel="stylesheet" href="../../assets/css/app.css"><link rel="stylesheet" href="../../assets/css/site.css"></head><body><header class="topbar"><div class="shell"><a class="brand" href="../../index.html"><span class="brand-mark">◆</span><span><b>PERSIA</b> · War Drone</span></a></div></header><main><section class="hero"><div class="shell"><span class="badge">PERSIA · DORE ${esc(String(target.snapshot_id).replace(/^S/,''))}</span><h1>جدول جامع عملکرد و تغییرات اعضای کلن</h1><p>${esc(target.date_persian)} · ساعت ${esc(target.time_iran)} · تمام ${faNumber(target.members)} عضو بررسی و ثبت شده‌اند.</p>${nav}</div></section><section class="section"><div class="shell"><h2>وضعیت کلی و شاخص‌های کلیدی کلن</h2><p>ظرفیت اعضا: ${faNumber(target.members)} از ${faNumber(target.capacity)} نفر${previous?` · دوره قبلی: ${esc(previous.time_iran)}`:''}.</p><ul><li>اعضای مشترک با دوره قبلی: ${faNumber(retained)} نفر</li><li>بازیکنان حذف‌شده: ${faNumber(removed.length)} · بازیکنان اضافه‌شده: ${faNumber(added.length)}</li><li>مدال کل کلن بر اساس مجموع رکورد اعضا: ${faNumber(totalClanMedals)}</li><li>بیشترین افزایش کیل: ${topKills.map(r=>`${esc(getName(r))} ${signed(r.kills_delta)}`).join(' · ')}</li><li>بیشترین افزایش مدال کلن: ${topLeague.map(r=>`${esc(getName(r))} ${signed(r.league_medals_delta)}`).join(' · ')}</li></ul><h2>جدول کامل رتبه‌بندی و تغییرات عملکرد اعضا</h2><div class="table-wrap"><table><thead><tr><th>رتبه</th><th>نام کاربری</th><th>سمت</th><th>استیج</th><th>مدال لیگ جاری</th><th>تغییر مدال کلن</th><th>مدال کل کلن</th><th>مدال افتخار (طلا / نقره / برنز)</th><th>مجموع کیل 💀</th><th>افزایش کیل 💀</th><th>لول سلاح‌ها (توپ / هیدرا / هل‌فایر)</th><th>آخرین آنلاین</th></tr></thead><tbody>${rowsHtml}</tbody></table></div>${nav}</div></section></main><footer class="site-footer"><div class="shell">Generated deterministically from canonical period ${esc(target.snapshot_id)} · source: ${esc(sourcePath)}</div></footer></body></html>`;
const outputArg=process.argv[3]||path.join(REPORTS,`${reportId(target)}.html`);fs.mkdirSync(path.dirname(outputArg),{recursive:true});fs.writeFileSync(outputArg,report,'utf8');console.log(JSON.stringify({ok:true,snapshot_id:snapshotId,output:outputArg,members:target.members,total_clan_medals:totalClanMedals,added:added.length,removed:removed.length},null,2));
